Moving average with explanatory variables
trustedanalytics/spark-tk pull request #148
Opened 2016-09-12 21:53 UTC by ekote

2016-09-14 16:39 UTC, dmsuehir commented on python/sparktk/models/timeseries/max.py
> +
Add documentation block w/ parameter list

2016-09-14 16:42 UTC, dmsuehir commented on python/sparktk/models/timeseries/max.py
> +        :param scala_model: (scala MAXModel) Scala model to load.
"MaxModel" instead of MAXModel, since that's how the class is named

2016-09-14 16:43 UTC, dmsuehir commented on python/sparktk/models/timeseries/max.py
> +        :return: (MAXModel) MAXModel object
Same as the line above -- MaxModel, not MAXModel

2016-09-14 16:43 UTC, dmsuehir commented on python/sparktk/models/timeseries/max.py
> +    def p(self):
Remove p, since it will always be 0 for MAX?

2016-09-14 16:44 UTC, dmsuehir commented on python/sparktk/models/timeseries/max.py
> +    def d(self):
Remove d, since is also always 0 for MAX?

2016-09-14 16:47 UTC, dmsuehir commented on sparktk-core/src/test/scala/org/trustedanalytics/sparktk/models/timeseries/max/MaxModelTest.scala
> +    new GenericRow(Array[Any](68, 278, 0, 28, 0.015132758079119)),
Is this the data from Kyle?  If so, we can't use it in the test - use Air Quality or something else instead

2016-09-14 21:10 UTC, ekote commented on python/sparktk/models/timeseries/max.py
> +
Done. Also at arimax.py

2016-09-14 21:39 UTC, ekote commented on python/sparktk/models/timeseries/max.py
> +        >>> xx = predicted_frame.take(3).data
bug

2016-09-14 23:57 UTC, dmsuehir commented on python/sparktk/models/timeseries/max.py
> +    """load MAXModel from given path"""
MaxModel instead of MAXModel

2016-09-15 00:02 UTC, dmsuehir requested changes
Estera, thanks for making the fixes.  I just made a note in load() where MAXModel should be changed to MaxModel.

2016-09-15 00:12 UTC, ekote commented on python/sparktk/models/timeseries/max.py
> +    """load MAXModel from given path"""
ok. done

2016-09-15 17:39 UTC, dmsuehir approved these changes

2016-09-16 17:58 UTC, merged