Updates the readme to have better information and better formatting.
trustedanalytics/spark-tk pull request #206
Opened 2016-10-04 19:50 UTC by lewisc

2016-10-04 19:51 UTC, lewisc reviewed
Trying to make the regression tests a little more accessible.

2016-10-04 19:55 UTC, lewisc commented
@sharibenko @akeller @danzsmith53 this represents some documentation updates for a sort of subproject of sparktk.

The regression tests represent a host of (theoretically) live examples on how to use sparktk, and exercises (again, theoretically) the entire API of sparktk in the python layer. These tests also attempt to validate the integration layer with CDH.

These tests DO NOT run any performance analysis. But overall, this is roughly a walkthrough of "how to start with Sparktk".

If this is misformatted or confusing, please let me know.

2016-10-04 21:24 UTC, sharibenko reviewed
I am looking into what the standards are for naming of sparktk.  You have in the body of this documentation "sparktk" but I am wondering if we need to institute a standard before we get too far in writing documentation for it.

2016-10-04 22:47 UTC, sharibenko requested changes
I just confirmed with Ling Yao that we should be using the following: "spark-tk library" as the official name for this tool.  Please updated the documentation to reflect this standard.

2016-10-04 22:56 UTC, akeller commented
Looks good @lewisc ! Coherent and easy to follow. @sharibenko makes a good point about a standard name for **spark-tk**. Clean that up and this is good to go!

2016-10-04 23:02 UTC, lewisc commented
For reference I believe @blbarker wanted the spark-tk to be sparktk (hence I did it this way). If you want his input we are going to have to wait until next week

2016-10-04 23:07 UTC, lewisc reviewed
Updated

2016-10-04 23:08 UTC, sharibenko commented
Is this internally or externally facing documentation?   Yes @blbarker established a standard for what we should call this tool internally among our team and "sparktk" was the final decision.  But Briton and I both agreed that when the time came we should establish how it should be written for externally facing documentation.  For that decision, I left it up to product management. Sorry for the confusion there!  If this is internally facing documentation only you can leave it as you have it.  If it is externally facing then we should change it to "spark-tk library"

2016-10-04 23:09 UTC, lewisc commented
It's public facing for sure, so it's spark-tk library/

2016-10-05 15:43 UTC, danzsmith53 commented on regression-tests/README.md
> +- The Python packages numpy, pytest, scipy, pandas and statsmodels must be installed - `pip2.7 install numpy scipy pandas statsmodels pytest`
insert comma after "pandas"

2016-10-05 15:44 UTC, danzsmith53 commented on regression-tests/README.md
> +Note: the following assumes development is being performed on a controller node of the CDH cluster (i.e. access to YARN and HDFS is available)
insert comma after "i.e."

2016-10-05 15:45 UTC, danzsmith53 commented on regression-tests/README.md
> +4. (Optional) Install the GraphFrames library to use the graph functionality. This is only necessary if you want to run the graph regressions, or leverage the graph functionality.
Remove comma after "regressions"

2016-10-05 15:47 UTC, danzsmith53 commented on regression-tests/README.md
> +5. To run the regression tests you can either enter find the tests under the `sparktkregtests/testcases` folders, or you can run the following command to run all regression tests.
Add comma after the first "tests"

2016-10-05 15:48 UTC, danzsmith53 commented on regression-tests/README.md
> +2. Set the environment variables necessary for the spark-tk to be used. These environment variables tell the spark-tk library where to find
add "library" after the first "spark-tk"

2016-10-05 15:49 UTC, danzsmith53 commented on regression-tests/README.md
> +2. Set the environment variables necessary for the spark-tk to be used. These environment variables tell the spark-tk library where to find
Never mind, you caught it in the 3rd commit

2016-10-05 21:08 UTC, lewisc commented
I believe this answers all the questions, thanks. Let me know if there's more.

2016-10-05 23:36 UTC, merged