do not merge
trustedanalytics/spark-tk pull request #346
Opened 2016-11-15 18:57 UTC by grehx

2017-01-10 21:00 UTC, lewisc requested changes

2017-01-10 21:00 UTC, lewisc commented on regression-tests/automation/metadata_test.py
> +        "Test metadata file does not have duplicates"
make these docstrings (triple quoted)

2017-01-10 21:00 UTC, lewisc commented on regression-tests/automation/metadata_test.py
> +        filename = self.get_local_dataset('metadata.txt')
again, construct absolute paths off of config.root

2017-01-10 21:00 UTC, lewisc commented on regression-tests/automation/metadata_test.py
> +        datasets.remove('metadata.txt')
config.root path

2017-01-10 21:00 UTC, lewisc commented on regression-tests/automation/metadata_test.py
> +        filename = self.get_local_dataset('metadata.txt')
config.root path

2017-01-10 21:00 UTC, lewisc commented on regression-tests/automation/metadata_test.py
> +        for file in os.listdir("../datasets"):
do the same thing here as in line 38

2017-01-10 21:16 UTC, lewisc commented on regression-tests/automation/metadata_test.py
> +        datasets.remove('metadata.txt')
whoops, nevermind on this.

2017-01-11 00:05 UTC, merged

2017-01-11 19:11 UTC, blbarker commented on regression-tests/automation/metadata_test.py
> +        datasets.remove('metadata.txt')
I don't think you need the "datasets" computation in this function?

2017-01-11 19:11 UTC, blbarker commented on regression-tests/automation/metadata_test.py
> +    def test_metadata_does_not_have_nonexistent_dataset(self):
This test appears to be a duplicate of the previous one.

2017-01-11 19:11 UTC, blbarker commented on regression-tests/automation/metadata_test.py
> +    def test_metadata_does_not_have_nonexistent_dataset(self):
In fact, it seems you could easily collapse all three into one test, with two asserts

2017-01-11 19:20 UTC, grehx commented on regression-tests/automation/metadata_test.py
> +    def test_metadata_does_not_have_nonexistent_dataset(self):
its easier to read the output when it errors when they're broken up, but yeah, I can collapse them

2017-01-11 19:27 UTC, grehx commented on regression-tests/automation/metadata_test.py
> +        datasets.remove('metadata.txt')
yeah I'll fix that