add scoring pipeline test
trustedanalytics/spark-tk pull request #391
Opened 2016-12-22 22:22 UTC by grehx

2017-01-10 19:46 UTC, lewisc requested changes

2017-01-10 19:46 UTC, lewisc commented on regression-tests/automation/run_tests.sh
> +py.test --boxed -n48 -v $MAINDIR/regression-tests -k naivebayes
revert this change

2017-01-10 19:46 UTC, lewisc commented on regression-tests/sparktkregtests/lib/scoring_utils.py
> +        #self.scoring_process = None
is this supposed to be commented out? If it's not wanted delete it.

2017-01-10 21:03 UTC, lewisc commented
Looks good

2017-01-21 00:03 UTC, blbarker submitted a review, later dismissed

2017-01-21 00:03 UTC, blbarker commented on regression-tests/automation/requirements.txt
> +kafka
These 3 should not be added --I don't see them being used?

2017-01-21 02:11 UTC, merged